<!DOCTYPE >
<html lang="En">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="Michael A. Dennis<michaeladennis@yahoo.com>">
    </head>
    <body>
        <h1>Voting is a great thing. Create a Ballot, let the people speak.</h1>
        
        <ul>            
            <li>Search</li>
            <li>Create Ballot</li>            
        </ul>
        <form onSubmit="ballotLookUp()">
            <label>Ballot Look-up<label>
            <input type="number" min=1 name="ballot_id" />
            <button type="submit">Search</button>
        </form>
    </body>
</html>
